### ISSUE TITLE
Port the engine to libpng 1.6 and newer

### ISSUE THREAD

**Issue by akien-mga** [godrin/antargis#2]
I get the following issues when trying to compile antargis against libpng 1.6 (which is the default version here on Mageia):

```
[akien@cauldron Release]$ LC_ALL=C make
[  1%] Building CXX object CMakeFiles/antlib.dir/lib/ag_png.cc.o
/home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc: In function 'void png_io_flush(png_structp)':
/home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc:52:16: warning: variable 'src' set but not used [-Wunused-but-set-variable]
     SDL_RWops *src;
                ^
/home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc: In function 'int IMG_SavePNG_RW(SDL_Surface*, SDL_RWops*)':
/home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc:188:17: error: invalid use of incomplete type 'png_info {aka struct png_info_def}'
     if (info_ptr->palette)
                 ^
In file included from /home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc:30:0:
/usr/include/png.h:595:16: error: forward declaration of 'png_info {aka struct png_info_def}'
 typedef struct png_info_def png_info;
                ^
/home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc:189:35: error: invalid use of incomplete type 'png_info {aka struct png_info_def}'
       checkedDeleteArray( info_ptr->palette);
                                   ^
In file included from /home/akien/Mageia/Sandbox/antargis/antargis-master/lib/ag_png.cc:30:0:
/usr/include/png.h:595:16: error: forward declaration of 'png_info {aka struct png_info_def}'
 typedef struct png_info_def png_info;
                ^
CMakeFiles/antlib.dir/build.make:517: recipe for target 'CMakeFiles/antlib.dir/lib/ag_png.cc.o' failed
make[2]: *** [CMakeFiles/antlib.dir/lib/ag_png.cc.o] Error 1
CMakeFiles/Makefile2:98: recipe for target 'CMakeFiles/antlib.dir/all' failed
make[1]: *** [CMakeFiles/antlib.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

My guess would be that it would work if I were to compile using libpng 1.2, but even though it's available in my repositories, since SDL_image requires libpng 1.6, the build system seems to try to use the latter no matter what.

I could have a go at patching the buildsystem so that it uses libpng12, but maybe it would be better to port antargis to libpng16 which is pretty standard nowadays?

I'm not a developer myself, but for some context about what would need to change to port to newer versions of libpng, you can see for example what Stratagus had to change: http://bazaar.launchpad.net/~stratagus/stratagus/trunk/revision/7993#src/video/png.cpp
